---
version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.3
  heroku: circleci/heroku@1.2.6

executors:
  rails-executor:
    docker:
      - image: cimg/ruby:3.1.2-browsers
        environment:
          RAILS_ENV: test
          POSTGRES_USERNAME: postgres
          POSTGRES_PASSWORD: password
      - image: cimg/redis:6.2.6
      - image: cimg/postgres:14.2
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: theodinproject_test
    working_directory: ~/theodinproject

commands:
  build-app:
    description: Building app
    steps:
      - checkout

      - run: gem install bundler:2.2.33
      - restore_cache:
          name: Restore bundle cache
          key: theodinproject-bundle-{{ checksum "Gemfile.lock" }}
      - restore_cache:
          name: Restore yarn cache
          key: theodinproject-yarn-{{ checksum "yarn.lock" }}
      - run: bundle install --path vendor/bundle
      - run: yarn install
      - save_cache:
          name: Store bundle cache
          key: theodinproject-bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - save_cache:
          name: Store yarn cache
          key: theodinproject-yarn-{{ checksum "yarn.lock" }}
          paths:
            - ~/.yarn-cache
      - run: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run: bundle exec rake db:schema:load

jobs:
  tests:
    executor: rails-executor
    steps:
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          command:
            google-chrome --version
            chromedriver --version
          name: Check install
      - build-app
      - run: yarn test
      - run: bundle exec rspec
  linters:
    executor: rails-executor
    steps:
      - build-app
      - run: bundle exec rubocop
      - run: yarn run eslint
  seeds:
    executor: rails-executor
    steps:
      - build-app
      - run:
          name: Seeds
          command: bin/rails db:seed

workflows:
  version: 2
  build:
    jobs:
      - tests
      - linters
      - seeds
      - heroku/deploy-via-git:
          force: true
          app-name: theodinproject
          branch: main
          requires:
            - tests
            - linters
            - seeds
          filters:
            branches:
              only:
                - main
