---
version: 2.1

executors:
  rails-executor:
    docker:
      - image: circleci/ruby:2.7.3-buster-node-browsers
        environment:
          RAILS_ENV: test
          POSTGRES_USERNAME: postgres
          POSTGRES_PASSWORD: password
      - image: circleci/redis:alpine
      - image: circleci/postgres:12.2-ram
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: theodinproject_test
    working_directory: ~/theodinproject

commands:
  build-app:
    description: Building app
    steps:
      - checkout

      - run: gem install bundler:1.17.3
      - restore_cache:
          name: Restore bundle cache
          key: theodinproject-bundle-{{ checksum "Gemfile.lock" }}
      - restore_cache:
          name: Restore yarn cache
          key: theodinproject-yarn-{{ checksum "yarn.lock" }}
      - run: bundle install --path vendor/bundle
      - run: yarn install
      - save_cache:
          name: Store bundle cache
          key: theodinproject-bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - save_cache:
          name: Store yarn cache
          key: theodinproject-yarn-{{ checksum "yarn.lock" }}
          paths:
            - ~/.yarn-cache
      - run: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run: bundle exec rake db:schema:load

jobs:
  tests:
    executor: rails-executor
    steps:
      - build-app
      - run: yarn test
      - run: bundle exec rspec
  linters:
    executor: rails-executor
    steps:
      - build-app
      - run: bundle exec rubocop
      - run: yarn run eslint
  seeds:
    executor: rails-executor
    steps:
      - build-app
      - run:
          name: Seeds
          command: bin/rails db:seed

workflows:
  version: 2
  build:
    jobs:
      - tests
      - linters
      - seeds
