blank_issues_enabled: true
contact_links:
  - name: ğŸ–¥ï¸ Website Bugs or Feature Requests
    url: https://github.com/TheOdinProject/theodinproject
    about: "This repository is for curriculum content. For changes to the site itself, check out Odin's web app repository"
  - name: ğŸ’¡ Ideas, Content Requests and Questions
    url: https://github.com/TheOdinProject/curriculum/discussions
    about: "Have an idea? Want to see content on a particular topic? Open a discussion here"
  - name: ğŸ’¬ Join the Discord Community
    url: https://discord.gg/fbFCkYabZB
    about: "Outside of GitHub, the Odin community lives on Discord. Join our server here"
